name: Server & Client CI/CD -- PROD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: feedbackcollectionserver    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './server'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.13.2'                # set this to the node version to use
 
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'

    - name: npm install, build server and client
      run: |
        cd server
        npm install
        npm run build --if-present
        npm run ci-postbuild
    
    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: list directory
      run: |
        file *

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        path: release.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2 

    - name: Unzip artifact
      run: |
        unzip artifact/release.zip
        file *

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
